cpi_fvg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('totem.urls')),
    path('totem/', include('totem.urls')),
    path('admin/', admin.site.urls),
]

totem/urls.py
from django.urls import path

from . import views

app_name = 'totem'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('content/<int:content_id>/', views.content, name='content'),
    path('info/<int:info_id>/', views.info, name='info'),
    path('map', views.mappa, name='map'),
    path('prova', views.prova, name='prova'),
]

totem/models.py
import datetime

from django.db import models
from django.utils import timezone

from ckeditor.fields import RichTextField
from colorful.fields import RGBColorField

LANGUAGES = (
    ('it', 'Italiano'),
    ('en', 'English'),
    ('slo', 'Slovenski jezik'),
    ('de', 'Deutsche sprache'),
    ('hrv', 'Hrvatski jezik'),
)

USER_ACTIONS = (
    (-1, '-'),
    (0, 'index'),
    (1, 'area'),
    (2, 'content'),
    (3, 'information')
)

class Category(models.Model):
    key = models.CharField(max_length=2)
    name = models.CharField(max_length=256)
    emoji = models.CharField(max_length=9, blank=True, null=True)
    description = models.CharField(max_length=256, blank=True, null=True, verbose_name="descrizione")

    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Categorie"

    def __str__(self):
        return "Category " + str(self.key) + ' (' + \
               str(self.name) + ') ' + str(self.emoji)


class FileItem(models.Model):
    file_field = models.FileField(upload_to='uploads/%Y/%m/%d/')
    upload_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        pass

    def __str__(self):
        return "" + str(self.id) + " : " + self.file_field.name + "" + self.upload_date.strftime(
            "%d/%m/%y")


class Office(models.Model):
    title = RichTextField(max_length=1024, verbose_name="nome dell'ufficio")

    class Meta:
        verbose_name = 'Ufficio'
        verbose_name_plural = 'Uffici'
    def __str__(self):
        return "Office " + str(self.id) + ' (' + \
               str(self.title) + ') '


class MapZone(models.Model):
    title = RichTextField(max_length=1024, verbose_name="nome della zona")

    color = RGBColorField(blank=True, null=True, )

    floor = models.CharField(max_length=1024, blank=True, null=True, verbose_name="piano")

    tag = models.CharField(max_length=1024, blank=True, null=True, verbose_name="tag identificativo")

    description = RichTextField(max_length=1024, blank=True, null=True, verbose_name="descrizione")

    class Meta:
        verbose_name = 'Zona della mappa'
        verbose_name_plural = 'Zone della mappa'

    def __str__(self):
        return "MapZone " + str(self.id) + ' (' + \
               str(self.tag) + ') '


class Area(models.Model):
    title = RichTextField(max_length=1024, verbose_name="nome dell'area")

    color = RGBColorField(blank=True, null=True, )

    office = models.ForeignKey(Office, on_delete=models.PROTECT, blank=True, null=True, verbose_name="dove?")

    image = models.ForeignKey(FileItem, on_delete=models.PROTECT, null=True, blank=True, verbose_name="immagine")

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='data inserimento')
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Area'
        verbose_name_plural = 'Aree'

    def __str__(self):
        return self.title

    @staticmethod
    def fill_default_areas():
        print("fill_default_areas")

        if len(Area.objects.all()) != 0:
            return False

        a = Area()
        a.title = "Accoglienza informazioni"
        a.save()

        a = Area()
        a.title = "Colloqui individuali"
        a.save()

        a = Area()
        a.title = "Laboratori di gruppo"
        a.save()

        a = Area()
        a.title = "Servizio incontro domanda offerta"
        a.save()

        a = Area()
        a.title = "Attivazione tirocini"
        a.save()

        return True


class Informations(models.Model):
    # area = models.ForeignKey(Area, on_delete=models.PROTECT, blank=True, null=True, verbose_name="area")
    where = models.ForeignKey(MapZone, on_delete=models.PROTECT, blank=True, null=True, verbose_name="dove?")
    when = RichTextField(max_length=1024, blank=True, null=True, verbose_name="quando?")
    how = RichTextField(max_length=1024, blank=True, null=True, verbose_name="come?")
    for_who = RichTextField(max_length=1024, blank=True, null=True, verbose_name="per chi?")

    class Meta:
        verbose_name = 'Informazioni'
        verbose_name_plural = 'Informazioni'

    def __str__(self):
        return "Info " + str(self.id)


class Content(models.Model):
    area = models.ForeignKey(Area, on_delete=models.CASCADE)

    title = RichTextField(max_length=1024, blank=True, null=True, verbose_name="titolo")
    # title = models.CharField(max_length=1024, blank=True, null=True, verbose_name="titolo")
    text = RichTextField(max_length=4096, blank=True, null=True, )

    image = models.ForeignKey(FileItem, on_delete=models.PROTECT, null=True, blank=True, verbose_name="immagine")

    categories = models.ManyToManyField(Category, blank=True, verbose_name="categorie")

    link = models.CharField(max_length=1024, blank=True, null=True)
    link_caption = models.CharField(max_length=1024, blank=True, null=True, default="continua")

    lang = models.CharField(max_length=3, choices=LANGUAGES, default='it',
                            verbose_name="lingua")

    linked_contents = models.ManyToManyField('Content', blank=True, verbose_name="contenuti collegati")

    level = models.SmallIntegerField(default=1)

    information = models.ForeignKey(Informations, on_delete=models.PROTECT, null=True, blank=True,
                                    verbose_name="dove, come, quando, per chi?")

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='data inserimento')
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Contenuto'
        verbose_name_plural = 'Contenuti'

    def __str__(self):
        return self.title


class UserAction(models.Model):
    session_id = models.CharField(max_length=64, blank=True, null=True)
    content_id = models.SmallIntegerField(default=-1)
    information_id = models.SmallIntegerField(default=-1)
    mapzone_id = models.SmallIntegerField(default=-1)

    # action_type = models.SmallIntegerField(default=-1, choices=USER_ACTIONS, default=-1)

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='data inserimento')
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.session_id)

totem/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import loader
from django.views import generic

from .models import Area, Content, UserAction, Informations


def content(request, content_id):
    if not request.session.session_key:
        request.session.create()

    print(request.session.session_key)

    ua = UserAction()
    ua.content_id = content_id
    ua.session_id = request.session.session_key
    ua.save()

    # content_text = Content.objects.all()
    content_text = get_object_or_404(Content, id=content_id)
    # content_text = Content.objects.get(pk=content_id)
    linked_content = Content.objects.filter(linked_contents__id=content_id)
    # linked_content = #get_object_or_404(Content, id=content_id)

    context = {'content_text': content_text,
               'linked_content': linked_content}
    return render(request, 'totem/content.html', context)


def info(request, info_id):
    area_id = request.GET.get('area_id', '-')
    content_id = request.GET.get('content_id', '-')

    # print(area_id)
    # print(content_id)

    info_text = get_object_or_404(Informations, id=info_id)
    content_instance = get_object_or_404(Content, id=content_id)

    context = {'info_text': info_text,
               'content': content_instance}

    return render(request, 'totem/info.html', context)


def mappa(request):
    return render(request, 'totem/map.html', {})

def prova(request):
    areas = []
    for area in Area.objects.order_by('id'):
        queryset = Content.objects.filter(area=area).order_by('id')

        area.contents = queryset
        areas.append(area)

    context = {'areas': areas}

    return render(request, 'totem/prova.html', context)



class IndexView(generic.View):

    def get(self, request, *args, **kwargs):

        if not request.session.session_key:
            request.session.create()
            request.session.set_expiry(120)  # set http session timeout (seconds)

            print(f"new sessionid: {request.session.session_key}")
        else:
            print(f"existing sessionid: {request.session.session_key}")

        ua = UserAction()
        ua.session_id = request.session.session_key
        # ua.action_type =
        ua.save()

        areas = []
        for area in Area.objects.order_by('id'):
            queryset = Content.objects.filter(area=area).order_by('id')

            area.contents = queryset
            areas.append(area)

        context = {'areas': areas}

        return render(request, 'totem/homepage.html', context)

totem/templates/totem/area.html
<div>
    <h2> {{ content_text.title }} </h2>
</div>

totem/templates/totem/content.html
{% load static %}

<style>
*{
    font-family: Verdana !important;
}

body {
    margin: 10px;
}
h2 {
   text-align: center;
   {% if content_text.area.color %}
   color: {{ content_text.area.color }};
   {% endif %}
}
.myul {
    justify-content: space-between;
    display: flex;
    list-style: none;
    padding: 15px;
    /*border: 1px solid #000;*/
    margin-right: 10%;
    margin-left: 10%;
}

.roundbox {
  text-align:justify;
  border-radius: 20px;
  border: 4px solid {% if content_text.area.color %} {{ content_text.area.color }}; {% endif %}
  padding: 20px;
  margin-top: 30px;
  margin-right: 10%;
  margin-bottom: 30px;
  margin-left: 10%;
  padding-top:5%;
  padding-bottom: 5%;
}

.mybtn {
  background-color: #f6f6f6;
  border: 2px solid {% if content_text.area.color %} {{ content_text.area.color }}; {% endif %}
  color: #333;
  padding: 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 8px;
  cursor: pointer;
  border-radius: 10px;
  box-shadow: box-shadow: 24px 4px 9px -4px rgba(0,0,0,0.4);
<!--  box-shadow: 2px 4px #888888;-->
}

</style>


{% autoescape off %}
<div>
<ul class="myul">
    <li style="float:left;"><h2> {{ content_text.title | striptags | title }} </h2></li>
    <li><a href="/info/{{content_text.information_id}}/?area_id={{content_text.area_id}}&content_id={{content_text.id}}" class="mybtn">Informazioni Aggiuntive</a>
    </li>
</ul>
</div>
<div class="roundbox">
   {{ content_text.text }}
</div>

<div>

   <ul class="myul">
   {% for linked in linked_content %}
            <a href="{% url 'totem:content' linked.id %}" class="mybtn">{{ linked.title | striptags | title}}</a>
   {% endfor %}
   </ul>
</div>

<div>
   <ul class="myul">
      <li><a href="{% url 'totem:index' %}" class="mybtn">INDIETRO</a></li>
      <li><a href="{% url 'totem:index' %}" class="mybtn">PAGINA INIZIALE</a></li>
      <li><a href="/map" class="mybtn">MAPPA</a></li>
   </ul>
</div>


{% endautoescape %}


<script src="{% static "totem/timeout.js" %}"></script>

totem/templates/totem/homepage.html
{% load static %}

{% autoescape off %}

<link rel="stylesheet" type="text/css" href="{% static 'totem/style.css' %}" />

<div class="content">
    <h1>SERVIZI ALLE PERSONE</h1>
    <figure class="content">

<!--                <ul class="cf">-->

              <ul class="father cf">
                <ul></ul>
                {% for area in areas %}

                <li class="macro_area num_{{ area.id }}">


                  <a href="#"><span>{{ area.title | striptags }}</span></a>
                  <ul class="sections">

                      {% for content in area.contents %}
                      {% if content.level == 1 %}

                        <li class="section"><a style="background-color: white;" href="content/{{ content.id }}/"><span>{{ content.title | striptags }}</span></a></li>

                      {% endif %}
                      {% endfor %}

                  </ul>
                </li>
                {% endfor %}

              </ul>

    </figure>

</div>

<div>
   <ul class="myul">
      <li style="margin-left:50%; margin-right:50%;"><a href="/map" class="mybtn">[prova]MAPPA</a></li>
   </ul>
</div>





{% endautoescape %}

totem/templates/totem/info.html
{% load static %}

{% autoescape off %}

<style>
*{
   font-family: Verdana !important;
}

.tab {
   border-collapse: separate;
   border-spacing: 10px 30px;
   width: 90%;
   margin-left:auto;
   margin-right:auto;
}

.tab td, #tab th {
   border: 2px solid;
   padding: 20px;
   border-radius: 15px;
}

/*

.tab tr:nth-child(even){background-color: #f2f2f2;}

.tab tr:hover {background-color: #ddd;}
*/


.tab th {
   padding-top: 12px;
   padding-bottom: 12px;
   text-align: left;
   background-color: rgb(255, 162, 161);
   color: white;
}
.titolo{
   color: {% if content.area.color %} {{ content.area.color }}; {% endif %}
   text-align: center;
   padding-top: 20px;
}

.tag{
   margin-left: 90%;
   float:inline-end;
   margin-inline-end: 20px;
}
.tag a{
   text-decoration:none;
   border: 2px solid red;
   padding: 20;
   border-radius: 50%;
   color: black;
   background-color: linen;
}

a:visited {
  color: black;
}


.myul {
    justify-content: space-between;
    display: flex;
    list-style: none;
    padding: 15px;
    /*border: 1px solid #000;*/
}

.mybtn {
  background-color: #f6f6f6;
  border: 2px solid {% if content.area.color %} {{ content.area.color }}; {% endif %}
  color: #333;
  padding: 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 8px;
  cursor: pointer;
  border-radius: 10px;
  box-shadow: box-shadow: 24px 4px 9px -4px rgba(0,0,0,0.4);
}

</style>

<div class="titolo">
   <h2> {{ content.area|striptags }}</h2>
</div>
<table class="tab">

   <tr>
      <td>DOVE</td>
      <td style="border:0;">
         <img src="{% static "totem/arrow50.png" %}" alt="arrow50">
      </td>
      <td>{{ info_text.where.title | striptags }}
         <div class="tag">
            <a href="{% url 'totem:map' %}"> {{ info_text.where.tag }} </a>
         </div>
      </td>
   </tr>
   <tr>
      <td>COME</td>
      <td style="border:0;">
         <img src="{% static "totem/arrow50.png" %}" alt="arrow50">
      </td>
      <td>{{ info_text.how }}</td>
   </tr>
   <tr>
      <td>QUANDO</td>
      <td style="border:0;">
         <img src="{% static "totem/arrow50.png" %}" alt="arrow50">
      </td>
      <td>{{ info_text.when }}</td>
   </tr>
   <tr>
      <td>PER CHI</td>
      <td style="border:0;">
         <img src="{% static "totem/arrow50.png" %}" alt="arrow50">
      </td>
      <td>{{ info_text.for_who }}</td>
   </tr>
</table>

<div>
   <ul class="myul">
      <li><a href="{% url 'totem:content'  content.id %}" class="mybtn">INDIETRO</a></li>
      <li><a href="{% url 'totem:index' %}" class="mybtn">PAGINA INIZIALE</a></li>
      <li><a href="{% url 'totem:map' %}" class="mybtn">MAPPA</a></li>
   </ul>
</div>


{% endautoescape %}

<script src="{% static "totem/timeout.js" %}"></script>

totem/templates/totem/map.html
{% load static %}
<style>
*{
   text-align: center;

}
.myul {
    justify-content: space-between;
    display: flex;
    list-style: none;
    padding: 15px;
    /*border: 1px solid #000;*/
}

.mybtn {
   background-color: #f6f6f6;
   border: 2px solid black;
   color: #333;
   padding: 20px;
   text-align: center;
   text-decoration: none;
   display: inline-block;
   font-size: 16px;
   margin: 4px 8px;
   cursor: pointer;
   border-radius: 10px;
   box-shadow: box-shadow: 24px 4px 9px -4px rgba(0,0,0,0.4);
}

</style>
<div>
    <img src="{% static 'totem/map1.png' %}" alt="mappa">
</div>


<div>
   <ul class="myul">
      <li style="margin-left:50%; margin-right:50%;"><a href="{% url 'totem:index' %}" class="mybtn" style="margin-top: -30px;" >PAGINA INIZIALE</a></li>
   </ul>
</div>

<script src="{% static "totem/timeout.js" %}"></script>

totem/templates/totem/prova.html
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/sankey.js"></script>
<script src="https://code.highcharts.com/modules/organization.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<style>
*{
   font-family: Verdana!Important;
}
.highcharts-figure, .highcharts-data-table table {
    min-width: 360px;
    max-width: 800px;
    margin: 1em auto;
}

.highcharts-data-table table {
	font-family: Verdana, sans-serif;
	border-collapse: collapse;
	border: 1px solid #EBEBEB;
	margin: 10px auto;
	text-align: center;
	width: 100%;
	max-width: 500px;
}
.highcharts-data-table caption {
    padding: 1em 0;
    font-size: 1.2em;
    color: #555;
}
.highcharts-data-table th {
	font-weight: 600;
    padding: 0.5em;
}
.highcharts-data-table td, .highcharts-data-table th, .highcharts-data-table caption {
    padding: 0.5em;
}
.highcharts-data-table thead tr, .highcharts-data-table tr:nth-child(even) {
    background: #f8f8f8;
}
.highcharts-data-table tr:hover {
    background: #f1f7ff;
}

#container h4 {
    text-transform: none;
    font-size: 14px;
    font-weight: normal;
}
#container p {
    font-size: 13px;
    line-height: 16px;
}

@media screen and (max-width: 600px) {
    #container h4 {
        font-size: 2.3vw;
        line-height: 3vw;
    }
    #container p {
        font-size: 2.3vw;
        line-height: 3vw;
    }
}
</style>



<figure class="highcharts-figure">
    <div id="container">
        <script>
            Highcharts.chart('container', {
            chart: {
                height: 600,
                inverted: true
            },

            title: {
                text: 'MAPPA DEI SERVIZI CPI'
            },

            accessibility: {
                point: {
                    descriptionFormatter: function (point) {
                        var nodeName = point.toNode.name,
                            nodeId = point.toNode.id,
                            nodeDesc = nodeName === nodeId ? nodeName : nodeName + ', ' + nodeId,
                            parentDesc = point.fromNode.id;
                        return point.index + '. ' + nodeDesc + ', reports to ' + parentDesc + '.';
                    }
                }
            },

            series: [{
                type: 'organization',
                name: 'Highsoft',
                keys: ['from', 'to'],
                data: [

                    {% for area in areas %}

                        {% for content in area.contents %}
                        {% if content.level == 1 %}

                            ['{{ area.title | striptags }}','{{ content.title | striptags | title }}' ],

                        {% endif %}
                        {% endfor %}

                    {% endfor %}


<!--                    ['CEO', 'CTO'],-->
<!--                    ['CEO', 'CPO'],-->
<!--                    ['CEO', 'CSO'],-->
<!--                    ['CEO', 'CMO'],-->
<!--                    ['CEO', 'HR'],-->
<!--                    ['CTO', 'Product'],-->
<!--                    ['CTO', 'Web'],-->
<!--                    ['CSO', 'Sales'],-->
<!--                    ['CMO', 'Market']-->
                ],
                levels: [{
                    level: 0,
                    color: 'silver',
                    dataLabels: {
                        color: 'black'
                    },
                    height: 25
                }, {
                    level: 1,
                    color: 'silver',
                    dataLabels: {
                        color: '#black'
                    },
                    height: 25
                }, {
                    level: 2,
                    color: '#980104'
                }, {
                    level: 4,
                    color: '#359154'
                }],


                nodes: [
                 {% for area in areas %}

                {
                    id: '{{ area.title | striptags }}',
                    title: '{{ area.title | striptags }}',
                    column:1,
                    layout: 'hanging',
                    level: 0
                },
                 {% endfor %}
                {
                    id: 'CEO',
                    title: 'CEO',
                    name: 'Grethe Hjetland',
                    image: 'https://wp-assets.highcharts.com/www-highcharts-com/blog/wp-content/uploads/2018/11/12132317/Grethe.jpg'
                }, {
                    id: 'HR',
                    title: 'HR/CFO',
                    name: 'Anne Jorunn Fjærestad',
                    color: '#007ad0',
                    image: 'https://wp-assets.highcharts.com/www-highcharts-com/blog/wp-content/uploads/2018/11/12132314/AnneJorunn.jpg',
                    column: 4,
                    offset: '75%'
                }, {
                    id: 'CTO',
                    title: 'CTO',
                    name: 'Christer Vasseng',
                    column: 1,
                    image: 'https://wp-assets.highcharts.com/www-highcharts-com/blog/wp-content/uploads/2018/11/12140620/Christer.jpg',
                    layout: 'hanging'
                }, {
                    id: 'CPO',
                    title: 'CPO',
                    name: 'Torstein Hønsi',
                    column: 4,
                    image: 'https://wp-assets.highcharts.com/www-highcharts-com/blog/wp-content/uploads/2018/11/12131849/Torstein1.jpg'
                }, {
                    id: 'CSO',
                    title: 'CSO',
                    name: 'Anita Nesse',
                    column: 4,
                    image: 'https://wp-assets.highcharts.com/www-highcharts-com/blog/wp-content/uploads/2018/11/12132313/Anita.jpg',
                    layout: 'hanging'
                }, {
                    id: 'CMO',
                    title: 'CMO',
                    name: 'Vidar Brekke',
                    column: 4,
                    image: 'https://wp-assets.highcharts.com/www-highcharts-com/blog/wp-content/uploads/2018/11/13105551/Vidar.jpg',
                    layout: 'hanging'
                }, {
                    id: 'Product',
                    name: 'Product developers'
                }, {
                    id: 'Web',
                    name: 'Web devs, sys admin'
                }, {
                    id: 'Sales',
                    name: 'Sales team'
                }, {
                    id: 'Market',
                    name: 'Marketing team'
                }],
                colorByPoint: false,
                color: '#007ad0',
                dataLabels: {
                    color: 'white'
                },
                borderColor: 'white',
                nodeWidth: 65
            }],
            tooltip: {
                outside: true
            },
            exporting: {
                allowHTML: true,
                sourceWidth: 800,
                sourceHeight: 600
            }

        });

    </script>

    </div>
    <p class="highcharts-description">
        Libreria free per uso non commerciale
    </p>
</figure>